name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Heroku Docker Registry
        run: echo ${{ secrets.HEROKU_API_KEY }} | docker login --username=_ --password-stdin registry.heroku.com
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Build Docker image
        run: docker build -t registry.heroku.com/networth-tracking/web .

      - name: Push Docker image to Heroku
        run: docker push registry.heroku.com/networth-tracking/web

      - name: Release the app on Heroku
        run: heroku container:release web --app networth-tracking
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
